module.exports = {
    catalogs: [
        {
            path: '<rootDir>/locale/{locale}/catalog',
            include: ['<rootDir>'],
        },
    ],
    compileNamespace: 'cjs',
    extractBabelOptions: {},
    fallbackLocales: {},
    format: 'minimal',
    sourceLocale: 'en',
    locales: [
        'de',
        'en',
        'es-AR',
        'es',
        'it',
        'ro',
        'ru',
        'vi',
        'zh-CN',
        'zh-TW',
        'ko',
        'ja',
        'fr',
    ],
    orderBy: 'messageId',
    pseudoLocale: '',
    rootDir: './src',
    runtimeConfigModule: ['@lingui/core', 'i18n'],
}
