name: CI

on:  
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          node-version: 14
          always-auth: true
          registry-url: https://registry.npmjs.org
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --version && yarn install --frozen-lockfile
        id: install

      - name: Run Unit tests
        run: yarn test:ci

      - name: Run E2E tests
        uses: mujo-code/puppeteer-headful@v2
        env:
          CI: 'true'
          TEST_PASS: ${{ secrets.TEST_PASS }}
          TEST_SEED: ${{ secrets.TEST_SEED }}
        with:
          args: yarn e2e
