name: Sync translations
on:
  push:
    branches:
      - master
      - canary
  pull_request:
    branches:
      - master
      - canary
    types: [closed]

jobs:
  translations:
    if: github.event.pull_request.merged == true
    name: Sync translations with sushiswap/translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          always-auth: true
          registry-url: https://registry.npmjs.org
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --version && yarn install --frozen-lockfile
        id: install

      - name: Checkout sushiswap/translations repository
        uses: actions/checkout@v2
        with:
          repository: sushiswap/translations
          path: translations

      - run: rm -rf locale
      - run: mv translations/sushiswap locale

      - name: Run LinguiJS
        run: npm run lingui

      - name: Remove compiled files
        run: rm -rf locale/*.js

      - name: Push translation files to translation repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'locale'
          destination-github-username: 'sushiswap'
          destination-repository-name: 'translations'
          user-email: ramin@sushi.com
          target-branch: master
          target-directory: sushiswap

      # Workaround to avoid Post Use step failures. See: https://github.com/actions/setup-node/issues/317
      - run: mkdir -p /home/runner/.cache/yarn/v6
        continue-on-error: true
